import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ToDoContextProvider } from '@/context/toDoContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <div className="w-full h-svh bg-custom-gray-600">
          <ToDoContextProvider>{children}</ToDoContextProvider>
        </div>
      </body>
    </html>
  )
}
